### PR TITLE
Readme edits

### LINKED ISSUE #2: Re-format the README file.

### LINKED ISSUE #3: update readme
Update the readme.md to show the description / objective / core features of the project

### PR DESCRIPTION
**Pull request by LiamBurchellReyes**
close #2
close #3
The readme has been updated to include all the team members' usernames. The readme includes the objectives and its description. The formatting has been updated.

### CODE REVIEW

**Review by steven-arsan — APPROVED** [review]
Everything looks good

**Review by jongjonathan — APPROVED** [review]
Updates and format look good

**Review by MatteoGisondi — APPROVED** [review]

**Review by alexbara2000 — APPROVED** [review]
everything looks good to me

**Review by JosephMezza — APPROVED** [review]
Looking good, all team members are now included.

**Pull request merged**
