### PR TITLE
Create basic flask template

### LINKED ISSUE #5: create the flask server
Create the basic python file that will act as our back-end page

### PR DESCRIPTION
**Pull request by MatteoGisondi**
Close #5

### CODE REVIEW

**Review by LiamBurchellReyes — APPROVED** [review]
Looks good to me!

**Review by alexbara2000 — COMMENTED** [review]
looks good to me

**Review by jongjonathan — APPROVED** [review]
Looking good!

**Review by alexbara2000 — APPROVED** [review]

**Review by JosephMezza — APPROVED** [review]
Great start for the back-end.

**Review by steven-arsan — APPROVED** [review]
Looks good

**Pull request merged**
